### ISSUE TITLE
Create groups without using the dashboard

### ISSUE THREAD

**Issue by vplasencia** [privacy-scaling-explorations/bandada#322] opened 2023-10-23 16:14 UTC
Right now to create a group you need to use the dashboard, it would be nice to create groups dynamically using code without using the dashboard.

**Comment by AtHeartEngineer** [comment] 2023-10-23 17:38
Ya we very much need this capability for discreetly. We will likely have 2 groups for most chat rooms, members, and admins

**Comment by aguzmant103** [comment] 2023-10-30 16:17
Might be a duplicate of #318

**Closed** 2023-10-30 16:17 UTC
Labels: feature :rocket:
